### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by Jarvizx** [james2doyle/pyro-list-field#5]
hi, you can debug pre_save();

**Comment by mamarmite** [comment]
Ok, I assume you talk about when the post is saved and fail, the list loose all its values?

If yes, I fixed that on line 36 of the field.list.php file
https://github.com/mamarmite/pyro-list-field/commit/4adfb5a07f78ab9aff3098018876684126ad917e

**Comment by mamarmite** [comment]
This is not an issue report. Please dig a bit in the issue at least.
If you talk about an issue on duplicate page with a list field, the field is double serialize, resulting on the value parse to be a string with the array value still string: `a:{`

The fix I add is on `pre_save()` function:

``` php
return gettype($input) === "string" ? $input : serialize($input); 
```

I fixed it on my fork: https://github.com/mamarmite/pyro-list-field 
Didn't do the pull request, James seem to be out of Github these day, I changed a bit the plugin too.

**Comment by Jarvizx** [comment]
Thz :+1:
